//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisticsSystem.Calculate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          Data Source=(DESCRIPTION=\r\n          (ADDRESS_LIST=(ADDRESS=(PROTOCOL" +
            "=TCP)(HOST=10.66.237.7)(PORT=1521)))\r\n          (CONNECT_DATA=(SERVICE_NAME=ORA1" +
            "0G)));\r\n          User Id=hbgctj;Password=hbgctj;\r\n        ")]
        public string conn_oracle {
            get {
                return ((string)(this["conn_oracle"]));
            }
            set {
                this["conn_oracle"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ggg")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
    }
}
